version: '2'

services:
    app:
        image: alpine
        command: ['true']
        volumes:
            - '${APP_DIR}:/var/www/current'
    www:
        build: www
        depends_on:
            - mysql
            - elasticsearch
        working_dir: /var/www/current
        ports:
            - ${WWW_PORT}:80
        links:
            - mysql
            - elasticsearch
        volumes_from:
            - app
        volumes:
            - './www/apache2/sites-available/:/etc/apache2/sites-available/'
            - './www/php/mods-available/xdebug.ini:/etc/php/7.0/mods-available/xdebug.ini'
            - './www/ssh/:/var/www/.ssh/' # For composer
        environment:
            DATABASE_HOST: mysql
            DATABASE_PORT: 3306
            DATABASE_NAME: ${MYSQL_DATABASE}
            DATABASE_USER: ${MYSQL_USER}
            DATABASE_PASSWORD: ${MYSQL_PASSWORD}
            ELASTICSEARCH_HOST: elasticsearch
            NODE_PATH: /usr/bin/nodejs
            NODE_UGLIFYJS_PATH: /usr/local/bin/uglifyjs
            NODE_UGLIFYCSS_PATH: /usr/local/bin/uglifycss
    mysql:
        image: mariadb
        ports:
            - 3307:3306
        volumes:
            - './data/mysql:/var/lib/mysql'
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    elasticsearch:
        image:  elasticsearch:2
        ports:
            - 9200
        volumes:
            - './data/elasticsearch:/usr/share/elasticsearch/data'
